using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MvpShop.Data.Migrations
{
    /// <inheritdoc />
    public partial class InitialProducts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Products" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" character varying(200) NOT NULL,
                    "Description" character varying(4000) NOT NULL,
                    "Price" numeric(18,2) NOT NULL,
                    "ImageUrl" character varying(1000),
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "Products";""");
        }
    }
}
