using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MvpShop.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddOrders : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Orders" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "CustomerName" character varying(200) NOT NULL,
                    "CustomerEmail" character varying(320) NOT NULL,
                    "CustomerPhone" character varying(50) NOT NULL,
                    "OrderDate" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "TotalAmount" numeric(18,2) NOT NULL,
                    "Status" character varying(32) NOT NULL
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "OrderItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "OrderId" integer NOT NULL,
                    "ProductId" integer NOT NULL,
                    "ProductName" character varying(200) NOT NULL,
                    "UnitPrice" numeric(18,2) NOT NULL,
                    "Quantity" integer NOT NULL,
                    CONSTRAINT "FK_OrderItems_Orders_OrderId"
                        FOREIGN KEY ("OrderId")
                        REFERENCES "Orders" ("Id")
                        ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_OrderItems_OrderId"
                ON "OrderItems" ("OrderId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "OrderItems";""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "Orders";""");
        }
    }
}
